language: node_js
node_js:
  - "9"
  - "10"
before_script:
  - npm run build
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npx version-from-git --travis
deploy:
  - provider: npm
    api_key:
      secure: "IxQsspvkjS6zdulIYxUvnVsz08SuesMwZYPHIhEAG6/XGRYJMgc+ec678hY8zXU1SZqaR1cWfixq1ib0EO0of5A5XIspAWgQs1dxXvgED/vzimN9JYRT5Kt+WV3Th4zm9pLejTPV7xjJVNPT9uohMLIslDH3cSp6pz187VxvAu3/jStGWsIJfR85e+I8LnnXJfnimAs58V2pAVoaBjak7f3PN1kMEXe3RUFb4/6T/05zrbTZtA3a+rRTLEGI6MstVoW9gxY4Pu9IKyCuUHQxpmFCi4OWtQ22LVfUxrFiGPaEhTGi0ClmrbaN9EeGsKx7f6i9ut6PdpNl5WMY8vkSYMdYyAwAfQ9P1UkZ7dhe/0rdYRwGAL3hcmQvrU2XQ6dN+EpuEGzsC3MBM49O7LcHwIay10rkixhpGAnkAdv+3r279yWDI6YEc1QpWdhIzTVKu41To/ZiIyKDrOn+Cim1EczoDU9uWvga2bdsY1Ob89DVqRg9CuIDPe4ZHGG2jC9slCzATTRABe3Rwo1zXyiui10bktWdZg9vWonNbA3lDYsFkLi0Qqk3zkZqoevVDQ3DURY6y2Jx9sktfevFhVa+R1zu7FSw5FvNqe+qxt9kjpid7vLa9cWY0UZskAu6mgxh5xXZHGDt2qWQzXRwQTMA7eVAKnqTRN3zg/V1qJ6yxWU="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "IxQsspvkjS6zdulIYxUvnVsz08SuesMwZYPHIhEAG6/XGRYJMgc+ec678hY8zXU1SZqaR1cWfixq1ib0EO0of5A5XIspAWgQs1dxXvgED/vzimN9JYRT5Kt+WV3Th4zm9pLejTPV7xjJVNPT9uohMLIslDH3cSp6pz187VxvAu3/jStGWsIJfR85e+I8LnnXJfnimAs58V2pAVoaBjak7f3PN1kMEXe3RUFb4/6T/05zrbTZtA3a+rRTLEGI6MstVoW9gxY4Pu9IKyCuUHQxpmFCi4OWtQ22LVfUxrFiGPaEhTGi0ClmrbaN9EeGsKx7f6i9ut6PdpNl5WMY8vkSYMdYyAwAfQ9P1UkZ7dhe/0rdYRwGAL3hcmQvrU2XQ6dN+EpuEGzsC3MBM49O7LcHwIay10rkixhpGAnkAdv+3r279yWDI6YEc1QpWdhIzTVKu41To/ZiIyKDrOn+Cim1EczoDU9uWvga2bdsY1Ob89DVqRg9CuIDPe4ZHGG2jC9slCzATTRABe3Rwo1zXyiui10bktWdZg9vWonNbA3lDYsFkLi0Qqk3zkZqoevVDQ3DURY6y2Jx9sktfevFhVa+R1zu7FSw5FvNqe+qxt9kjpid7vLa9cWY0UZskAu6mgxh5xXZHGDt2qWQzXRwQTMA7eVAKnqTRN3zg/V1qJ6yxWU="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "MjDlChMrCFwil4lO+IY00deLhPMZqIEs0dGZvqmiDFAmN9VHqAepyhg3/B5z1j//raAxDRjIlY3MVSckYkKwr+vqhB6CKbTzcn5e0g2jqg5IAwVaIIxWB7l8uCvZJ+vShf5jrvKYDKMWgHn4e8OtlkpvFno1zuH8fdXo5ysL9BllOY1Hx+5cU8W3UyWovBMlcv2Mphsg2ujK6olNRikY7XX26ZExi9VsYzoNtQjQeHx3aHlulJKfQvFq0K6sPX+l9yHd31orLzHdqtSg4pUGULpGzMNhDOs3fQ0VVAg9zYdmLdzNJ0Wwimzjr5RMXa+vdVJCyuFjf3LzhrOeGa3LKDSLLOObKCKza73hqi4VTF0180jFu5sQl0buZxcGU+QNHK6i+vdPjqFJeh9SRspo6gBd82rVEE3oK5lPLPAdZXZpBFwLOA9nADsSv90Y7hz3+0H2dZ7QHSBQVxVa5It3nRaJwcGiVrZh7gnVTvfBcGgkvca2rCRrYbX4KDuawG2vYiuHLwbPhnfHqvK2vzw2ctPejSXFHOigB7IaO0YCZSl3L2CUghiGtMTiLBHZY8NpBC8G/N11Z3SnKdThFq6WUOUCw+cyNdAkL3cu5pRhpCTCv/q9p4HLAa65lROS6UmMRZgAvgJuB5qtyBoBLTCb+BLhDXwz+fdog2zABwZ/9Wc="
    on:
      tags: true
    skip_cleanup: true
