language: node_js

node_js:
  - "10"

before_script:
  - npm run build

before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npx version-from-git --travis

deploy:
  - provider: npm
    api_key:
      secure: "XxXdz1+5VnR0GvLIDqj8W1olaXuXcLZ1tNPZ7+WeUDPOLERkBG+Aq/vu90+8DeIMTzFqEOMjp4TvcqhiGkTN3GRVL/XXHIejN0lyDrTpHcZ+0l+ogCkLYMlj0iktycmJ3t12olBfM/LAFYoV9VurcUYyhKG/SAJMfJh+Dg3hZVGr89GKe1aEIzRA9rLtRx8AhIMxZANRziaqSmAKkvfTJZuWow+X1nYijb5pYGiCSDsIhziWWBHXLr7hcL03yz8niHdPrjL9ntEkpUhvs6ZOL7rD7G4/9Y5kJ75tP53wehIiGqCuo3M7jEeu2OU0JaqPHZpzk4m7OcWKCSn1jOMS3NbIvfkW+Uw+vtz7v0dQZquQYdfT6LJMEg9vDJhU8VxUFimG0a6c8OzzPofcumthMheDDSDu3PYKkEEYHT9XyNk4qKYKtefcAGfGKZJdOsy0jRQf7i3jzTfOOT2wUDpvfQLSOxf+crjoH4cyxFAwGWJ22FtC8Ks4F2y3Iyh8R6c86ghcBjEL/IwMz5pBhDIIiVpYdDqkRGu+Q9QXRv93pkgKEz/3yzMCe8ck5NTgKb7gfNkfRFY+u64U03jLye2Y53DVw1Ctm7FZrRjXKw374cX30UE94dwbMIzlYQp0zPhIchnC8qdtsv8EQb3In+IWzkFqfnXoPlkX4rKW7Slr/Gs="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "XxXdz1+5VnR0GvLIDqj8W1olaXuXcLZ1tNPZ7+WeUDPOLERkBG+Aq/vu90+8DeIMTzFqEOMjp4TvcqhiGkTN3GRVL/XXHIejN0lyDrTpHcZ+0l+ogCkLYMlj0iktycmJ3t12olBfM/LAFYoV9VurcUYyhKG/SAJMfJh+Dg3hZVGr89GKe1aEIzRA9rLtRx8AhIMxZANRziaqSmAKkvfTJZuWow+X1nYijb5pYGiCSDsIhziWWBHXLr7hcL03yz8niHdPrjL9ntEkpUhvs6ZOL7rD7G4/9Y5kJ75tP53wehIiGqCuo3M7jEeu2OU0JaqPHZpzk4m7OcWKCSn1jOMS3NbIvfkW+Uw+vtz7v0dQZquQYdfT6LJMEg9vDJhU8VxUFimG0a6c8OzzPofcumthMheDDSDu3PYKkEEYHT9XyNk4qKYKtefcAGfGKZJdOsy0jRQf7i3jzTfOOT2wUDpvfQLSOxf+crjoH4cyxFAwGWJ22FtC8Ks4F2y3Iyh8R6c86ghcBjEL/IwMz5pBhDIIiVpYdDqkRGu+Q9QXRv93pkgKEz/3yzMCe8ck5NTgKb7gfNkfRFY+u64U03jLye2Y53DVw1Ctm7FZrRjXKw374cX30UE94dwbMIzlYQp0zPhIchnC8qdtsv8EQb3In+IWzkFqfnXoPlkX4rKW7Slr/Gs="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "MjDlChMrCFwil4lO+IY00deLhPMZqIEs0dGZvqmiDFAmN9VHqAepyhg3/B5z1j//raAxDRjIlY3MVSckYkKwr+vqhB6CKbTzcn5e0g2jqg5IAwVaIIxWB7l8uCvZJ+vShf5jrvKYDKMWgHn4e8OtlkpvFno1zuH8fdXo5ysL9BllOY1Hx+5cU8W3UyWovBMlcv2Mphsg2ujK6olNRikY7XX26ZExi9VsYzoNtQjQeHx3aHlulJKfQvFq0K6sPX+l9yHd31orLzHdqtSg4pUGULpGzMNhDOs3fQ0VVAg9zYdmLdzNJ0Wwimzjr5RMXa+vdVJCyuFjf3LzhrOeGa3LKDSLLOObKCKza73hqi4VTF0180jFu5sQl0buZxcGU+QNHK6i+vdPjqFJeh9SRspo6gBd82rVEE3oK5lPLPAdZXZpBFwLOA9nADsSv90Y7hz3+0H2dZ7QHSBQVxVa5It3nRaJwcGiVrZh7gnVTvfBcGgkvca2rCRrYbX4KDuawG2vYiuHLwbPhnfHqvK2vzw2ctPejSXFHOigB7IaO0YCZSl3L2CUghiGtMTiLBHZY8NpBC8G/N11Z3SnKdThFq6WUOUCw+cyNdAkL3cu5pRhpCTCv/q9p4HLAa65lROS6UmMRZgAvgJuB5qtyBoBLTCb+BLhDXwz+fdog2zABwZ/9Wc="
    on:
      tags: true
    skip_cleanup: true
